### ISSUE TITLE
SQLite in-memory

### ISSUE THREAD

**Issue by maximzasorin** [byjg/migration#23]
Hello, is it possible to use the library with SQLite in-memory database? I want to use the in-memory database in tests.

**Comment by byjg** [comment]
Hello, yes it is. 

you just need to create your Migration instance with the uri:

```
sqlite://:memory:
```

**Comment by maximzasorin** [comment]
Thank you, I did it. As part of testing after the migration, I need to perform queries to the created tables. Because the in-memory database exists only as part of a connection, I had to perform both the migration and queries using a single PDO instance. I thought that there was a way to pass the PDO instance into the migration, so I realized that there was no way. But this was the solution that suited me:
```php
$pdo = $migration->getDbDriver()->getDbConnection();
```

**Comment by byjg** [comment]
You are correct in that case. The in-memory database does not exists after the connection ends. Unfortunately I can't set the PDO connection to the migration object because I have to guarantee that the parameters the component needs were set and I need that the PDO connection matches with the Migration Commands, otherwise I'll get some errors. 

Anyway, I'm glad that get the connection this way solve your problem.
